/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedCategoryImport } from './routes/_authed/category'
import { Route as AuthedCategoryNameImport } from './routes/_authed/category.$name'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedCategoryRoute = AuthedCategoryImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedCategoryNameRoute = AuthedCategoryNameImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AuthedCategoryRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_authed/category': {
      id: '/_authed/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof AuthedCategoryImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/category/$name': {
      id: '/_authed/category/$name'
      path: '/$name'
      fullPath: '/category/$name'
      preLoaderRoute: typeof AuthedCategoryNameImport
      parentRoute: typeof AuthedCategoryImport
    }
  }
}

// Create and export the route tree

interface AuthedCategoryRouteChildren {
  AuthedCategoryNameRoute: typeof AuthedCategoryNameRoute
}

const AuthedCategoryRouteChildren: AuthedCategoryRouteChildren = {
  AuthedCategoryNameRoute: AuthedCategoryNameRoute,
}

const AuthedCategoryRouteWithChildren = AuthedCategoryRoute._addFileChildren(
  AuthedCategoryRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCategoryRoute: typeof AuthedCategoryRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCategoryRoute: AuthedCategoryRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/category': typeof AuthedCategoryRouteWithChildren
  '/category/$name': typeof AuthedCategoryNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/category': typeof AuthedCategoryRouteWithChildren
  '/category/$name': typeof AuthedCategoryNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/category': typeof AuthedCategoryRouteWithChildren
  '/_authed/category/$name': typeof AuthedCategoryNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/signup'
    | '/category'
    | '/category/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/signup'
    | '/category'
    | '/category/$name'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/category'
    | '/_authed/category/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/login",
        "/logout",
        "/signup"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/category"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_authed/category": {
      "filePath": "_authed/category.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/category/$name"
      ]
    },
    "/_authed/category/$name": {
      "filePath": "_authed/category.$name.tsx",
      "parent": "/_authed/category"
    }
  }
}
ROUTE_MANIFEST_END */
