name: ⚔️ `check` before merge to main

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get pnpm cache directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "::set-output name=dir::$(pnpm store path)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run check command
        run: pnpm run check

      - name: Comment on PR if check fails
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: github.context.pullRequest.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: 'Check failed. Please fix before merging.'
            })
